services:
  pulse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pulse-server
    ports:
      - "3030:3030/udp"
    networks:
      - pulse-net


networks:
  pulse-net:
    driver: bridge